# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2790528c064365d4909b120988bfb90f80f885b58f8f7e61fcf16376ba39ad2c6f9445bb81ad5ed7b642ece41b78aa30baae8ee2c2280aa5f05adc7ac57bc78f

test:
  secret_key_base: e4211ae3a0017c796f9db822934e0cdad7848020f3ae6532fb3fff7aa20d1467a6291771655282f6a577b0fa589f2f8f950f7c5bb50e341a9fea5736667e4078

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
